package org.castlekong.backend.entity

enum class GroupPermission {
    GROUP_MANAGE,
    MEMBER_READ,
    MEMBER_APPROVE,
    MEMBER_KICK,
    ROLE_READ,
    ROLE_MANAGE,
    CHANNEL_READ,
    CHANNEL_WRITE,
    CHANNEL_MANAGE,
    CHANNEL_INVITE,
    POST_CREATE,
    POST_READ,
    POST_UPDATE_OWN,
    POST_DELETE_OWN,
    POST_DELETE_ANY,
    COMMENT_CREATE,
    COMMENT_READ,
    RECRUITMENT_CREATE,
    RECRUITMENT_UPDATE,
    RECRUITMENT_DELETE,
}
