// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/comment/presentation/widgets/comment_input_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/features/comment/domain/entities/comment.dart' as _i2;
import 'package:frontend/features/comment/domain/usecases/create_comment_usecase.dart'
    as _i5;
import 'package:frontend/features/comment/domain/usecases/get_comments_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeComment_0 extends _i1.SmartFake implements _i2.Comment {
  _FakeComment_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCommentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCommentsUseCase extends _i1.Mock
    implements _i3.GetCommentsUseCase {
  MockGetCommentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Comment>> call(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [postId]),
            returnValue: _i4.Future<List<_i2.Comment>>.value(<_i2.Comment>[]),
          )
          as _i4.Future<List<_i2.Comment>>);
}

/// A class which mocks [CreateCommentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCommentUseCase extends _i1.Mock
    implements _i5.CreateCommentUseCase {
  MockCreateCommentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Comment> call({
    required int? postId,
    required String? content,
    int? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #postId: postId,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue: _i4.Future<_i2.Comment>.value(
              _FakeComment_0(
                this,
                Invocation.method(#call, [], {
                  #postId: postId,
                  #content: content,
                  #parentCommentId: parentCommentId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Comment>);
}
