// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/channel/data/repositories/channel_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/features/channel/data/datasources/channel_remote_data_source.dart'
    as _i4;
import 'package:frontend/features/channel/data/models/channel_dto.dart' as _i3;
import 'package:frontend/features/channel/data/models/channel_permissions_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChannelPermissionsDto_0 extends _i1.SmartFake
    implements _i2.ChannelPermissionsDto {
  _FakeChannelPermissionsDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannelDto_1 extends _i1.SmartFake implements _i3.ChannelDto {
  _FakeChannelDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChannelRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRemoteDataSource extends _i1.Mock
    implements _i4.ChannelRemoteDataSource {
  MockChannelRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.ChannelDto>> getChannels(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, [workspaceId]),
            returnValue: _i5.Future<List<_i3.ChannelDto>>.value(
              <_i3.ChannelDto>[],
            ),
          )
          as _i5.Future<List<_i3.ChannelDto>>);

  @override
  _i5.Future<_i2.ChannelPermissionsDto> getMyPermissions(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyPermissions, [channelId]),
            returnValue: _i5.Future<_i2.ChannelPermissionsDto>.value(
              _FakeChannelPermissionsDto_0(
                this,
                Invocation.method(#getMyPermissions, [channelId]),
              ),
            ),
          )
          as _i5.Future<_i2.ChannelPermissionsDto>);

  @override
  _i5.Future<_i3.ChannelDto> createChannel({
    required String? workspaceId,
    required String? name,
    required String? type,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [], {
              #workspaceId: workspaceId,
              #name: name,
              #type: type,
              #description: description,
            }),
            returnValue: _i5.Future<_i3.ChannelDto>.value(
              _FakeChannelDto_1(
                this,
                Invocation.method(#createChannel, [], {
                  #workspaceId: workspaceId,
                  #name: name,
                  #type: type,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ChannelDto>);
}
