// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/channel/domain/usecases/enter_channel_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:frontend/features/channel/domain/entities/channel.dart' as _i3;
import 'package:frontend/features/channel/domain/entities/channel_permissions.dart'
    as _i2;
import 'package:frontend/features/channel/domain/repositories/channel_repository.dart'
    as _i6;
import 'package:frontend/features/channel/domain/repositories/read_position_repository.dart'
    as _i8;
import 'package:frontend/features/post/domain/entities/pagination.dart' as _i4;
import 'package:frontend/features/post/domain/entities/post.dart' as _i5;
import 'package:frontend/features/post/domain/repositories/post_repository.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChannelPermissions_0 extends _i1.SmartFake
    implements _i2.ChannelPermissions {
  _FakeChannelPermissions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChannel_1 extends _i1.SmartFake implements _i3.Channel {
  _FakeChannel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePagination_2 extends _i1.SmartFake implements _i4.Pagination {
  _FakePagination_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePost_3 extends _i1.SmartFake implements _i5.Post {
  _FakePost_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChannelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannelRepository extends _i1.Mock implements _i6.ChannelRepository {
  MockChannelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i3.Channel>> getChannels(String? workspaceId) =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, [workspaceId]),
            returnValue: _i7.Future<List<_i3.Channel>>.value(<_i3.Channel>[]),
          )
          as _i7.Future<List<_i3.Channel>>);

  @override
  _i7.Future<_i2.ChannelPermissions> getMyPermissions(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getMyPermissions, [channelId]),
            returnValue: _i7.Future<_i2.ChannelPermissions>.value(
              _FakeChannelPermissions_0(
                this,
                Invocation.method(#getMyPermissions, [channelId]),
              ),
            ),
          )
          as _i7.Future<_i2.ChannelPermissions>);

  @override
  _i7.Future<_i3.Channel> createChannel({
    required String? workspaceId,
    required String? name,
    required String? type,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChannel, [], {
              #workspaceId: workspaceId,
              #name: name,
              #type: type,
              #description: description,
            }),
            returnValue: _i7.Future<_i3.Channel>.value(
              _FakeChannel_1(
                this,
                Invocation.method(#createChannel, [], {
                  #workspaceId: workspaceId,
                  #name: name,
                  #type: type,
                  #description: description,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.Channel>);
}

/// A class which mocks [ReadPositionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadPositionRepository extends _i1.Mock
    implements _i8.ReadPositionRepository {
  MockReadPositionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<int?> getReadPosition(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getReadPosition, [channelId]),
            returnValue: _i7.Future<int?>.value(),
          )
          as _i7.Future<int?>);

  @override
  _i7.Future<void> updateReadPosition(int? channelId, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#updateReadPosition, [channelId, position]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> getUnreadCount(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [channelId]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<int, int>> getAllReadPositions(List<int>? channelIds) =>
      (super.noSuchMethod(
            Invocation.method(#getAllReadPositions, [channelIds]),
            returnValue: _i7.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i7.Future<Map<int, int>>);

  @override
  _i7.Future<void> saveAndRefreshUnreadCount(int? channelId, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#saveAndRefreshUnreadCount, [
              channelId,
              position,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i9.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<(List<_i5.Post>, _i4.Pagination)> getPosts(
    String? channelId, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPosts,
              [channelId],
              {#page: page, #size: size},
            ),
            returnValue: _i7.Future<(List<_i5.Post>, _i4.Pagination)>.value((
              <_i5.Post>[],
              _FakePagination_2(
                this,
                Invocation.method(
                  #getPosts,
                  [channelId],
                  {#page: page, #size: size},
                ),
              ),
            )),
          )
          as _i7.Future<(List<_i5.Post>, _i4.Pagination)>);

  @override
  _i7.Future<_i5.Post> getPost(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i7.Future<_i5.Post>.value(
              _FakePost_3(this, Invocation.method(#getPost, [postId])),
            ),
          )
          as _i7.Future<_i5.Post>);

  @override
  _i7.Future<_i5.Post> createPost(String? channelId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [channelId, content]),
            returnValue: _i7.Future<_i5.Post>.value(
              _FakePost_3(
                this,
                Invocation.method(#createPost, [channelId, content]),
              ),
            ),
          )
          as _i7.Future<_i5.Post>);

  @override
  _i7.Future<_i5.Post> updatePost(int? postId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [postId, content]),
            returnValue: _i7.Future<_i5.Post>.value(
              _FakePost_3(
                this,
                Invocation.method(#updatePost, [postId, content]),
              ),
            ),
          )
          as _i7.Future<_i5.Post>);

  @override
  _i7.Future<void> deletePost(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
