// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/channel/domain/usecases/get_batch_unread_counts_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frontend/features/channel/domain/repositories/read_position_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReadPositionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadPositionRepository extends _i1.Mock
    implements _i2.ReadPositionRepository {
  MockReadPositionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int?> getReadPosition(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getReadPosition, [channelId]),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<void> updateReadPosition(int? channelId, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#updateReadPosition, [channelId, position]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getUnreadCount(int? channelId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [channelId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Map<int, int>> getAllReadPositions(List<int>? channelIds) =>
      (super.noSuchMethod(
            Invocation.method(#getAllReadPositions, [channelIds]),
            returnValue: _i3.Future<Map<int, int>>.value(<int, int>{}),
          )
          as _i3.Future<Map<int, int>>);

  @override
  _i3.Future<void> saveAndRefreshUnreadCount(int? channelId, int? position) =>
      (super.noSuchMethod(
            Invocation.method(#saveAndRefreshUnreadCount, [
              channelId,
              position,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
