name: univ_group_management
description: 대학 그룹 관리 Flutter 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP 통신
  dio: ^5.3.2
  
  # 상태 관리
  provider: ^6.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # 라우팅
  go_router: ^12.1.1
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # 의존성 주입
  get_it: ^7.6.4
  
  # 유틸리티
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  
  # UI
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 코드 생성
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  
  # 린팅
  flutter_lints: ^3.0.0
  
  # 테스트
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
